### ISSUE TITLE
[Bug] Empty config file

### ISSUE THREAD

**Issue by Hardeh** [slayer6409/Emergency-Dice-Updated#3]
Config file generates in configs/Emergency Dice.cfg, but it's completely empty

**Comment by slayer6409** [comment]
It is possible that it is a mod conflict or something, since I am not able to replicate the issue. Are you able to send me a log from when you launch the game, or a thunderstore code for the profile you are using?

In the meantime while I check on this issue, Here is the [Default Config](https://github.com/slayer6409/Emergency-Dice-Updated/blob/master/Emergency%20Dice.cfg) so you can replace it to get it to generate.

**Comment by dLogan807** [comment]
The conflicting mod seems to be [LethalPerformance](https://thunderstore.io/c/lethal-company/p/DiFFoZ/LethalPerformance/). 
If there is no config already, then only an empty file is generated. If a config already existed, then only configuration values and section headings are kept (no descriptive text). This behaviour happens on game launch.
Profile code: 0191ea2e-7d1c-b106-2e77-cbc9224e2329

**Comment by slayer6409** [comment]
I believe I have fixed the issue, and pushed out a new update, I will leave this issue open for a bit in case I overlooked something.

**Comment by dLogan807** [comment]
This does seem to be fixed - I can no longer reproduce the issue :D Cheers
